# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    program_builder.yml                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: umeneses <umeneses@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/05/09 19:12:18 by umeneses          #+#    #+#              #
#    Updated: 2024/06/28 19:08:07 by umeneses         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

name: program_builder

on:
  push:
    branches:
    - main
    - '**feature**'
    - '**bugfix**'
    - '**release**'
  pull_request:
    branches:
    - main
    - '**feature**'
    - '**bugfix**'
    - '**release**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./program_to_test/
    steps:
      - name: Starting github actions
        uses: actions/checkout@v4.1.4
      
      - name: Setup Valgrind
        run: sudo apt-get update | sudo apt-get install -y valgrind

      - name: Building Program with Push_Swap Makefile
        run: make
      
      - name: Running Valgrind
        run: valgrind --track-origins=yes --leak-check=full -q ./push_swap 42 -2 10 -10 11 77 666 2147483647 -2147483648
