# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    program_builder.yml                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: umeneses <umeneses@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/05/09 19:12:18 by umeneses          #+#    #+#              #
#    Updated: 2024/06/03 19:22:22 by umeneses         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

name: program_builder

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./program_to_test/
    steps:
      - name: Starting github actions
        uses: actions/checkout@v4.1.4
      
      - name: Building Program with Push_Swap Makefile
        run: make
