# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    tester_program.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: umeneses <umeneses@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/05/09 19:12:18 by umeneses          #+#    #+#              #
#    Updated: 2024/05/22 12:31:44 by umeneses         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

name: tester_program

on:
  push:
    branches:
    - main
    - 'feature/**'
    - 'bugfix/**'
    - 'release/**'
  pull_request:
    branches:
    - main
    - 'feature/**'
    - 'bugfix/**'
    - 'release/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./_ci_tdd/
    steps:
      - name: Starting github actions
        uses: actions/checkout@v4.1.4

      - name: Setup CUnit
        run: sudo apt-get update && sudo apt-get install -y libcunit1 libcunit1-doc libcunit1-dev

      - name: Running Tester Makefile
        run: make
        
      - name: Setup Valgrind
        run: sudo apt-get update | sudo apt-get install -y valgrind
      
      - name: Running Valgrind
        run: valgrind --leak-check=full ./push_swap.tests

      - name: Running Norminette
        run: norminette -R CheckForbiddenSourceHeader headers/ libs/ src/
      


# :: github actions documentation ::
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions